import type { Metadata } from 'next'
import './globals.css'

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const Layout = ({
  children,
}: Readonly<{
  children: React.ReactNode
}>) => {
  return (
    <html lang='en'>
      <body>{children}</body>
    </html>
  )
}

export { metadata }
export default Layout
